mysite/customer_reviews/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<supplier_slug>[a-zA-Z0-9\-]+)/$', views.supplier_reviews, name='supplier_reviews'),
    url(r'^(?P<supplier_slug>[a-zA-Z0-9\-]+)/write/$', views.supplier_review_create, name='supplier_review_create'),
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'mysite.views.home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^reviews/', include('customer_reviews.urls', namespace='customer_reviews')),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/customer_reviews/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class CustomerReview(models.Model):
    # Factor Data (implementation just happens to be numeric)
    # ENUM for greater flexibility
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    supplier = models.ForeignKey('suppliers.Supplier')
    author = models.CharField(max_length=60)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)
    review = models.CharField(max_length=1000)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    published = models.DateTimeField(editable=True, blank=True, null=True)

    def __unicode__(self):
        return self.review

    def isPublished(self):
        if (self.published and self.published <= timezone.now()):
            return True
        else:
            return False
    isPublished.admin_order_field = 'published'
    isPublished.boolean = True
    isPublished.short_description = 'Is Published?'

mysite/suppliers/models.py
from django.db import models

# TODO: Supplier slugs to be unique or choose another method for this

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.name

mysite/customer_reviews/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.utils import timezone
from suppliers.models import Supplier
from .models import CustomerReview

# Create your views here.
def index(request):
    suppliers = Supplier.objects.all().order_by('name')
    context = {'suppliers': suppliers}
    return render(request, 'customer_reviews/index.html', context)

def supplier_reviews(request, supplier_slug):
    supplier = Supplier.objects.get(slug=supplier_slug)
    reviews = CustomerReview.objects.filter(
            supplier__slug=supplier_slug
        ).exclude(
            published__gt=timezone.now()
        ).exclude(
            published__isnull=True
        ).order_by('-published')
    context = {'reviews': reviews, 'supplier': supplier}
    return render(request, 'customer_reviews/reviews.html', context)

def supplier_review_create(request, supplier_slug):
    supplier = Supplier.objects.get(slug=supplier_slug)
    context = {'supplier': supplier}
    if (request.POST):
        # Process data
        try:
            c = CustomerReview(
                supplier=supplier,
                author=request.POST['author'],
                review=request.POST['review'],
            )
            if (request.POST.get('rating')):
                c.rating = request.POST['rating']
            # Validate the model
            c.full_clean()
        except ValidationError as err:
            # No need to make the token obvious
            form_data = request.POST.copy()
            del form_data['csrfmiddlewaretoken']
            return render(request, 'customer_reviews/review-form.html', {
                'supplier': supplier,
                'choices': CustomerReview.RATING_CHOICES,
                'form_data': form_data,
                'errors': err,
            })
        else:
            # Submission was successful
            c.save()
            return HttpResponseRedirect(reverse('customer_reviews:supplier_reviews', args=(supplier_slug,)))
    else:
        # Serve up the form
        context['choices'] = CustomerReview.RATING_CHOICES
        return render(request, 'customer_reviews/review-form.html', context)

def supplier_review_process(request, supplier_slug):
    supplier = get_object_or_404(Supplier, slug=supplier_slug)
    context = {'supplier': supplier, 'choices': CustomerReview.RATING_CHOICES}
    return render(request, 'customer_reviews/review-form.html', context)

mysite/mysite/views.py
from django.shortcuts import render

def home(request):
    context = {}
    return render(request, 'customer_reviews/landing.html', context)

mysite/customer_reviews/templates/customer_reviews/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Reviews{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
      <style>
        body {
            padding-top: 50px;
        }
        .starter-template {
          padding: 40px 15px;
          text-align: center;
        }
      </style>
    <!-- Custom styles for this template -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Customer Reviews</a>
        </div>
      </div>
    </div>

    <div class="container">
    {% block content %}{% endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  </body>
</html>

mysite/customer_reviews/templates/customer_reviews/index.html
{% extends "base.html" %}

{% block title %}Suppliers{% endblock %}

{% block content %}
{% if suppliers %}
  <ul style="list-style-type: none;">
  {% for supplier in suppliers %}
    <li>
      <h3>{{ supplier.name }}</h3>
      <p><a class="btn btn-primary"
            href="{% url 'customer_reviews:supplier_reviews' supplier.slug %}"
            role="button">Reviews</a></p>
    </li>
    <hr>
  {% endfor %}
{% else %}
  <p>There aren't any suppliers to review yet!</p>
{% endif %}
{% endblock %}

mysite/customer_reviews/templates/customer_reviews/landing.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div>
    <h1>Supplier Reviews</h1>
    <p class="lead"><a class="btn btn-success" href="/reviews">Click Me</a></p>
</div>
{% endblock %}

mysite/customer_reviews/templates/customer_reviews/review-form.html
{% extends "base.html" %}

{% block title %}Review {{ supplier.name }}{% endblock %}

{% block content %}
<h3 xmlns="http://www.w3.org/1999/html">Review {{ supplier.name }}</h3>
{% if errors %}
<p>{{ errors }}</p>

{% for field in errors %}
    {{ field
    {% for err in field %}
        {{ err }}
    {% endfor %}
{% endfor %}

{% endif %}
<form action="{% url 'customer_reviews:supplier_review_create' supplier.slug %}"
      class="jumbotron"
      style="padding: 30px;"
      method='POST'>
    {% csrf_token %}
    <label class="has-error">Rating</label>
    <div>
        {% for value, string in choices %}
        <div class="radio-inline">
            <label>
                <input type="radio"
                       name="rating"
                       {% if form_data.rating %}
                            {%if form_data.rating == string %}
                       checked="checked"
                            {% endif %}
                       {% endif %}
                       value="{{ value }}">
              {{ string }}
            </label>
        </div>
        {% endfor %}
    </div>
    <div class="form-group">
        <label>Review</label>
        <textarea name="review"
                  class="form-control {% if errors.review %}has-error{% endif %}"
                  rows="5"
                  placeholder="Enter your Review..."
        >{% if form_data.review %}{{ form_data.review }}{% endif %}</textarea>
    </div>
    <div class="form-group">
        <label>Your Name</label>
        <input type="text"
               class="form-control"
               name="author"
               value="{%if form_data.author %}{{ form_data.author }}{% endif %}"
               placeholder="Davey Jones...">
    </div>
    <button class="btn btn-success btn-lg btn-block"
            type="submit">Submit</button>
</form>
{% endblock %}

mysite/customer_reviews/templates/customer_reviews/reviews.html
{% extends "base.html" %}

{% block title %}{{ supplier.name }}{% endblock %}

{% block content %}
  <h2>{{ supplier.name }} Reviews:</h2>
{% if reviews %}
  <h3>Reviews for {{ supplier.name }}</h3>
  {% for review in reviews %}

      <div class="panel panel-default">
          <div class="panel-heading"><strong>{{ review.author }}</strong> said:
              <span class="pull-right">{{ review.created }}</span></div>
          <div class="panel-body">
             <p class="lead">{{ review.rating }}</p>
              <div>
                  {{ review.review }}
              </div>
          </div>
       </div>

  {% endfor %}
{% else %}
  <p>There aren't any published reviews for {{ supplier.name }} yet!</p>
{% endif %}

<hr>
<p><a class="btn btn-success" href="/reviews/{{ supplier.slug }}/write/">Add Review</a></p>
<p><a href="/reviews/">Back to Suppliers</a></p>

{% endblock %}